service: plugin-test

plugins:
  - serverless-newrelic-alerts

custom:
  newrelic:
    incidentPreference: 'PER_CONDITION'
    policyServiceToken: arn:aws:test-infrastructure_condition_service_token 
    #arn:aws:lambda:us-east-1:577152972443:function:infrastructure-new-relic-alerts-alert-policy-dev
    infrastructureConditionServiceToken: arn:aws:test-infrastructure_condition_service_token
    #arn:aws:lambda:us-east-1:577152972443:function:infrastructure-new-relic-alerts-infrastructure-alert-dev
    violationCloseTimer: 24
    definitions:
      customAlert1:
        namespace: 'AWS::Lambda::Function'
        title: 'Custom Alert 1'
        runbookURL: 'https://aws.amazon.com/lambda/'
        metric: 'provider.4xxError.Sum'
        violationCloseTimer: 4
        criticalThreshold:
          value: 5
          duration: 300
        comparison: above
    alerts:
      - type: functionDuration1Sec
        title: 'Duration 1 sec'
        runbookURL: 'https://aws.amazon.com/lambda/'
      - functionErrors
      - type: apiGateway4XXErrors
        enabled: true
      - apiGateway5XXErrors
      - type: sqsDlqVisibleMessages
        filter: '-dlq'
      - type: dynamoDbSystemErrors
        enabled: false
     # - dynamoDbUserErrors

provider:
  name: aws
  runtime: nodejs12.x
  stage: test

functions:
  ga-lambda:
    handler: index.endpoint
    events:
      - http:
          path: test
          method: get
    alerts:
      - functionThrottles

  dummy-lambda:
    handler: index.endpoint
    alerts:
      - type: functionThrottles
        title: 'Dummy Throttles'
        runbookURL: 'https://aws.amazon.com/lambda/'
      - functionErrors

  test-lambda:
    handler: index.endpoint
    alerts:
      - type: functionDuration1Sec
        enabled: false

resources:
  Resources:
    TestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: test-sqs

    TestDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: test-sqs-dlq

    DynamoDbTestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: test-table
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
