service: plugin-test

plugins:
  - serverless-newrelic-alerts

custom:
  newrelicAlerts:
    policyServiceToken: arn:aws:test-policy_service_token
    infrastructureConditionServiceToken: arn:aws:test-infrastructure_condition_service_token
    alerts:
      - functionDuration1Sec
      - functionErrors
      - functionThrottles

provider:
  name: aws
  runtime: nodejs12.x
  stage: test

functions:
  under-newrelic-mntrng:
    handler: index.endpoint

  dummy-lambda:
    handler: index.endpoint
