service: plugin-test

plugins:
  - serverless-newrelic-alerts

custom:
  newrelicAlerts:
    policyServiceToken: arn:aws:lambda:us-east-1:577152972443:function:infrastructure-new-relic-alerts-alert-policy-dev
    infrastructureConditionServiceToken: arn:aws:lambda:us-east-1:577152972443:function:infrastructure-new-relic-alerts-infrastructure-alert-dev
    alerts:
      - functionDuration1Sec
      - functionErrors
      - apiGateway4XXErrors
      - apiGateway5XXErrors
      - dlqVisibleMessages

provider:
  name: aws
  runtime: nodejs12.x
  stage: test

functions:
  under-newrelic-mntrng:
    handler: index.endpoint
    events:
      - http:
          path: test
          method: get
    alerts:
      - functionThrottles

  dummy-lambda:
    handler: index.endpoint
    alerts:
      - name: functionThrottles
        enabled: true
      - functionErrors

  test-lambda:
    handler: index.endpoint
    alerts:
      - name: functionDuration1Sec
        enabled: false

resources:
  Resources:
    TestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: test-sqs

    TestDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: test-sqs-dlq
