service: plugin-test

plugins:
  - serverless-newrelic-alerts

custom:
  newrelicAlerts:
    policyServiceToken: arn:aws:test-policy_service_token
    infrastructureConditionServiceToken: arn:aws:test-infrastructure_condition_service_token
    alerts:
      - functionDuration1Sec
      - functionErrors
      - apiGateway4XXErrors
      - apiGateway5XXErrors
      - sqsDlqVisibleMessages
      - dynamoDbSystemErrors
      - dynamoDbUserErrors

provider:
  name: aws
  runtime: nodejs12.x
  stage: test

functions:
  under-newrelic-mntrng:
    handler: index.endpoint
    events:
      - http:
          path: test
          method: get
    alerts:
      - functionThrottles

  dummy-lambda:
    handler: index.endpoint
    alerts:
      - name: functionThrottles
        enabled: true
      - functionErrors

  test-lambda:
    handler: index.endpoint
    alerts:
      - name: functionDuration1Sec
        enabled: false

resources:
  Resources:
    TestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: test-sqs

    TestDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: test-sqs-dlq

    DynamoDbTestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: test-table
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
