service: plugin-test

plugins:
  - serverless-newrelic-alerts

custom:
  newrelicAlerts:
    policyServiceToken: arn:aws:test-policy_service_token
    infrastructureConditionServiceToken: arn:aws:test-infrastructure_condition_service_token
    alerts:
      - functionDuration1Sec
      - functionErrors

provider:
  name: aws
  runtime: nodejs12.x
  stage: test

functions:
  under-newrelic-mntrng:
    handler: index.endpoint
    alerts:
      - functionThrottles

  dummy-lambda:
    handler: index.endpoint
    alerts:
      - name: functionThrottles
        enabled: true
      - functionErrors

  test-lambda:
    handler: index.endpoint
    alerts:
      - name: functionDuration1Sec
        enabled: false
