version: 2

defaults: &defaults
  docker:
    - image: circleci/node:14.15.1

jobs:
  lint_commit_message:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run:
          name: Define environment variable with lastest commit's message
          command: |
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Lint commit message
          command: echo "$COMMIT_MESSAGE" | npx commitlint
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run:
          name: Run tests
          command: npm run test:prod
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && npm whoami
      - run:
          name: Publish package
          command: npm run semantic-release

workflows:
  version: 2
  test-n-deploy:
    jobs:
      - lint_commit_message
      - test
      - deploy:
          requires:
            - lint_commit_message
            - test
          filters:
            branches:
              only:
                - main
